version: "3.9"
name: media-stack
include:
  - radarr/radarr.docker-compose.yml
  - sonarr/sonarr.docker-compose.yml
  - bazarr/bazarr.docker-compose.yml
  - prowlarr/prowlarr.docker-compose.yml
  - overseerr/overseerr.docker-compose.yml
  - deluge/deluge.docker-compose.yml
  - transmission/transmission.docker-compose.yml
  - plex/plex.docker-compose.yml

volumes:
  nas-share:
    name: nas-share
    driver_opts: &driver-default
      type: cifs
      o: username=${NET_USER?err},password=${NET_USER_PASSWORD?err},rw,uid=1000,gid=1000
      device: ${NAS_MACHINE:?err}/Server
  nas-share-media-extra:
    name: nas-share-media-extra
    driver_opts:
      <<: *driver-default
      device: ${NAS_MACHINE:?err}/Media-Extra

networks:
  media:
    name: ${NETWORK_NAME:-media-network}
    driver: bridge
