version: "3.9"
name: media-stack
include:
  - radarr/radarr-compose.yml
  - sonarr/sonarr-compose.yml
  - bazarr/bazarr-compose.yml
  - prowlarr/prowlarr-compose.yml
  - overseerr/overseerr-compose.yml
  - deluge/deluge-compose.yml
  - plex/plex-compose.yml

volumes:
  nas-share-downloads:
    name: nas-share-downloads
    driver_opts: &driver-default
      type: cifs
      o: username=${NET_USER?err},password=${NET_USER_PASSWORD?err},rw,uid=1000,gid=1000
      device: ${NAS_MACHINE:?err}/downloads
  nas-share-movies:
    name: nas-share-movies
    driver_opts:
      <<: *driver-default
      device: ${NAS_MACHINE:?err}/movies
  nas-share-shows:
    name: nas-share-shows
    driver_opts:
      <<: *driver-default
      device: ${NAS_MACHINE:?err}/shows
  nas-share-library:
    name: nas-share-library
    driver_opts:
      <<: *driver-default
      device: ${NAS_MACHINE:?err}/plex-library

networks:
  media:
    name: ${NETWORK_NAME:-media-network}
