version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  proxied-media:
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    volumes:
      - ${SERVER_CONFIG_DIR?:err}/${SERVICE_NAME:?err}:/config:rw
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    networks:
      - media