version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  plex:
    container_name: ${SERVICE_NAME:?err}
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - HOSTNAME=${HOST_NAME:?err}
      #- PLEX_CLAIM=${PLEX_CLAIM-}
    volumes:
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows
      - ../../../config/${SERVICE_NAME}:/config