version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  plex:
    hostname: ${HOST_NAME:?err}
    container_name: ${SERVICE_NAME:?err}
    image: lscr.io/linuxserver/plex:latest
    environment:
      - VERSION=docker
      - HOSTNAME=${HOST_NAME:?err}
      - PLEX_CLAIM=${PLEX_CLAIM-}
    ports:
      - ${SERVICE_PORT}:32400/tcp
      - 3005:3005/tcp 
      - 8324:8324/tcp 
      - 32469:32469/tcp 
      - 1900:1900/udp 
      - 32410:32410/udp 
      - 32412:32412/udp 
      - 32413:32413/udp 
      - 32414:32414/udp 
    volumes:
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows