version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  plex:
    extends:
      file: ../proxied-media-service.yml
      service: proxied-media
    hostname: ${HOST_NAME:?err}
    network_mode: host
    container_name: ${SERVICE_NAME:?err}
    image: lscr.io/linuxserver/plex:latest
    environment:
      - VERSION=docker
      - HOSTNAME=${HOST_NAME:?err}
      - PLEX_CLAIM=${PLEX_CLAIM-}
    volumes:
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows