version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  plex:
    container_name: ${SERVICE_NAME:?err}
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - nas-share-library:/config
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows