version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  plex:
    extends:
      file: ../proxied-media-service.docker-compose.yml
      service: proxied-media
    container_name: ${SERVICE_NAME:?err}
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - VERSION=docker
      - HOSTNAME=${HOST_NAME:?err}
      - ADVERTISE_IP=https://${SERVICE_NAME}.${HOST_ADDRESS}
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - ${WEBUI_PORT_EXTERNAL}:32400/tcp
    volumes:
      - nas-share:/data
      - nas-share-media-extra:/media-extra
      - nas-share-library:/config
    networks:
      proxy:
        ipv4_address: 192.168.32.15