version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  plex:
    extends:
      file: ../proxied-media-service.yml
      service: proxied-media
    container_name: ${SERVICE_NAME:?err}
    image: lscr.io/linuxserver/plex:latest
    environment:
      - VERSION=docker
      - hostname=${HOST_NAME:?err}
    ports:
      - ${SERVICE_PORT}:32400/tcp
    volumes:
      - nas-share-library:/config
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows