version: "3.9"
name: portainer

volumes:
  nginx-data:
  portainer-data:

networks:
  home-lab:

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000
      - ${PORTAINER_PORT}:9443
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - home-lab

  nginx:
    container_name: nginx_proxy_manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    ports: 
      - 80:80
      - ${NGINX_PROXY_MANAGER_PORT}:81
      - 443:443
    volumes:
      - nginx-data:/data
      - nginx-data:/etc/letsencrypt
    networks:
      - home-lab