version: "3.9"
name: home-lab
include:
  - stacks/network/network-stack.docker-compose.yml
  - stacks/security/security-stack.docker-compose.yml
  - stacks/dashboard/dashboard-stack.docker-compose.yml
  - stacks/media/media-stack.docker-compose.yml
  - stacks/server-management/server-management-stack.docker-compose.yml
  - stacks/home/home-stack.docker-compose.yml
