version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  cadvisor:
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ${SERVICE_NAME:?err}
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    networks:
      - monitoring