version: "3.9"
name: network-stack
include:
  - traefik/traefik.docker-compose.yml
  - adguard-home/adguard-home.docker-compose.yml

networks:
  proxy:
    name: "proxy"
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.32.0/24
          gateway: 192.168.32.1