version: "3.9"
name: media-lab
services:

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: always
    environment:
      - UMASK=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    ports:
      - ${DELUGE_PORT}:8112
      - 58846:58846
      - 58946:58946/udp
    volumes:
      - deluge-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: always
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - sonarr-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-shows:/data/shows

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: always
    environment:
      - UMASK=022 #optional
      - PUID=1000
      - PGID=1000
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - radarr-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-movies:/data/movies

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: always
    ports:
      - ${BAZARR_PORT}:6767
    volumes:
      - bazarr-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: always
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - prowlarr-config:/config

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: always
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${OVERSEERR_PORT}:5055
    volumes:
      - overseerr-config:/config

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - nas-share-library:/config
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows

volumes:
  sonarr-config:
    name: sonarr-config
  radarr-config:
    name: radarr-config
  deluge-config:
    name: deluge-config
  bazarr-config:
    name: bazarr-config
  prowlarr-config:
    name: prowlarr-config
  overseerr-config:
    name: overseerr-config
  nas-share-downloads:
    name: nas-share-downloads
    driver_opts: &driver-default
      type: cifs
      o: username=${NET_USER},password=${NET_USER_PASSWORD?err},rw,uid=1000,gid=1000
      device: ${NAS_MACHINE}/downloads
  nas-share-movies:
    name: nas-share-movies
    driver_opts:
      <<: *driver-default
      device: ${NAS_MACHINE}/movies
  nas-share-shows:
    name: nas-share-shows
    driver_opts:
      <<: *driver-default
      device: ${NAS_MACHINE}/shows
  nas-share-library:
    name: nas-share-library
    driver_opts:
      <<: *driver-default
      device: ${NAS_MACHINE}/plex-library

networks:
  default:
    name: $NETWORK_NAME
