version: "3.9"
name: media-lab
volumes:
  sonarr-config:
  radarr-config:
  deluge-config:
  bazarr-config:
  prowlarr-config:
  overseerr-config:
  portainer-data:
  nas-share-downloads: 
    driver_opts: &driver-default
      type: cifs
      o: username=${NET_USER},password=${NET_USER_PASSWORD?err},rw,uid=1000,gid=1000
      device: ${NET_MACHINE}/downloads
  nas-share-movies:
    driver_opts:
      <<: *driver-default
      device: ${NET_MACHINE}/movies
  nas-share-shows:
    driver_opts:
      <<: *driver-default
      device: ${NET_MACHINE}/shows
networks:
  home-lab:
services:

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    environment:
      - UMASK=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    ports:
      - ${DELUGE_PORT}:8112
      - 58846:58846
      - 58946:58946/udp
    volumes:
      - deluge-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows
    networks:
      - home-lab

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - sonarr-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-shows:/data/shows
    networks:
      - home-lab

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - UMASK=022 #optional
      - PUID=1000
      - PGID=1000
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - radarr-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-movies:/data/movies
    networks:
      - home-lab

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    ports:
      - ${BAZARR_PORT}:6767
    volumes:
      - bazarr-config:/config
      - nas-share-downloads:/data/downloads
      - nas-share-movies:/data/movies
      - nas-share-shows:/data/shows
    networks:
      - home-lab

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - prowlarr-config:/config
    networks:
      - home-lab

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${OVERSEERR_PORT}:5055
    volumes:
      - overseerr-config:/config
    networks:
      - home-lab