version: "3.9"
name: media-lab
volumes:
  sonarr-config:
  radarr-config:
  deluge-config:
  bazarr-config:
  prowlarr-config:
  overseerr-config:
  portainer-data:
networks:
  home-lab:
services:

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: always
    environment:
      - UMASK=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    ports:
      - ${DELUGE_PORT}:8112
      - 58846:58846
      - 58946:58946/udp
    volumes:
      - deluge-config:/config
      - ${DATA_DIRECTORY}/torrents:/data/downloads
      - ${MEDIA_DIRECTORY}/movies:/data/movies
      - ${MEDIA_DIRECTORY}/shows:/data/shows
      - ${MEDIA_DIRECTORY}/books:/data/books
      - ${MEDIA_DIRECTORY}/podcasts:/data/podcasts
    networks:
      - home-lab

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: always
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - sonarr-config:/config
      - ${MEDIA_DIRECTORY}/shows:/shows
    networks:
      - home-lab

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: always
    environment:
      - UMASK=022 #optional
      - PUID=1000
      - PGID=1000
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - radarr-config:/config
      - ${MEDIA_DIRECTORY}/movies:/movies
    networks:
      - home-lab

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: always
    ports:
      - ${BAZARR_PORT}:6767
    volumes:
      - bazarr-config:/config
      - ${MEDIA_DIRECTORY}/movies:/movies
      - ${MEDIA_DIRECTORY}/shows:/shows
    networks:
      - home-lab

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: always
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - prowlarr-config:/config
    networks:
      - home-lab

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    restart: always
    ports:
      - ${OVERSEERR_PORT}:5055
    volumes:
      - overseerr-config:/app/config
    networks:
      - home-lab