version: '3.9'
name: ${SERVICE_NAME:?err}
services:
  traefik:
    extends:
      file: ${PWD}/proxied-service.yml
      service: proxied
    image: traefik:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - ${EXPOSED_PORT:-80}:80
      - 443:443
    environment:
      - CF_API_EMAIL=${DNS_EMAIL:?err}
      - CF_DNS_API_TOKEN=${CF_API_TOKEN:?err}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.http.middlewares.${SERVICE_NAME:?err}-auth.basicauth.users=${USER:?err}:${HASHED_PASSWORD:?err}"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${SERVICE_NAME:?err}-secure.middlewares=${SERVICE_NAME:?err}-auth"
      - "traefik.http.routers.${SERVICE_NAME:?err}-secure.tls.domains[0].main=${HOST_ADDRESS:?err}"
      - "traefik.http.routers.${SERVICE_NAME:?err}-secure.tls.domains[0].sans=*.${HOST_ADDRESS:?err}"
      - "traefik.http.routers.${SERVICE_NAME:?err}-secure.service=api@internal"

networks:
  proxy:
    name: proxy
