version: '3.9'
name: ${SERVICE_NAME:?err}
services:
  adguard-home:
    extends:
      file: ../../../proxied-service.docker-compose.yml
      service: proxied
    container_name: ${SERVICE_NAME:?err}
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp # DHCP
      # - 68:68/tcp # DHCP
      # - 68:68/udp # DHCP
      - ${EXPOSED_PORT}:80/tcp
      - 444:443/tcp
      - 444:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
    volumes:
      - ../../../config/${SERVICE_NAME}:/opt/adguardhome/conf
      - ../../../data/${SERVICE_NAME}:/opt/adguardhome/work
    networks:
      proxy:
        ipv4_address: 192.168.32.99