version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  bazarr:
    extends:
      file: ../proxied-media-service.docker-compose.yml
      service: proxied-media
    image: lscr.io/linuxserver/bazarr:latest
    volumes:
      - nas-share-movies:/data/movies:rw
      - nas-share-shows:/data/shows:rw