version: "3.9"
services:
  duplicati:
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    image: lscr.io/linuxserver/duplicati:latest
    volumes:
      - ${SERVER_CONFIG_DIR?:err}/${SERVICE_NAME}:/config
      - ${SERVER_CONFIG_DIR?:err}:/source/config
      - ${SERVER_DATA_DIR?:err}:/source/data
      - ${SERVER_DIR?:err}/backups:/backups