version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  grafana:
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    image: grafana/grafana-enterprise
    user: '1000'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${SERVER_DATA_DIR?:err}/${SERVICE_NAME}:/var/lib/grafana:rw
    networks:
      - monitoring