version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  deluge:
    extends:
      file: ../proxied-media-service.docker-compose.yml
      service: proxied-media
    image: ebrianne/docker-deluge-openvpn
    environment:
      - DELUGE_LOGLEVEL=info #optional
      - DELUGE_DOWNLOAD_DIR=/data/downloads
      - DELUGE_INCOMPLETE_DIR=/data/downloads
      - DELUGE_TORRENT_DIR=/config/torrents
      - DELUGE_WATCH_DIR=/config/watch
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER?:err}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG?:err}
      - OPENVPN_USERNAME=${OPENVPN_USER?:err}
      - OPENVPN_PASSWORD=${OPENVPN_PASS?:err}
      - LOCAL_NETWORK=192.168.50.0/24
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - ${LOADBALANCE_PORT}:8112
    volumes:
      - nas-share:/data

  deluge-exporter:
    container_name: deluge-exporter
    image: tobbez/deluge_exporter:latest
    environment:
      - DELUGE_HOST=deluge
      - DELUGE_PORT=58846
      - DELUGE_USER=exporter
      - DELUGE_PASSWORD=${DELUGE_PASSWORD?:err}
    volumes:
      - ${SERVER_CONFIG_DIR?:err}/${SERVICE_NAME}:/root/.config/deluge/
    networks:
      - media
      - monitoring
