version: "3.9"
services:
  prometheus:
    extends:
      file: ../../../proxied-service.docker-compose.yml
      service: proxied
    image: prom/prometheus:latest
    privileged: true
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # - '--storage.tsdb.path=/prometheus'
      # - '--web.console.libraries=/etc/prometheus/console_libraries'
      # - '--web.console.templates=/etc/prometheus/consoles'
      # - '--web.enable-lifecycle'
    volumes:
      - ${SERVER_CONFIG_DIR:?err}/${SERVICE_NAME?:err}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # - ${SERVER_DATA_DIR:?err}/${SERVICE_NAME?:err}:/prometheus
    depends_on:
      - cadvisor
    networks:
      - monitoring