version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  paperless:
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    depends_on:
      - redis
    environment:
      PAPERLESS_REDIS: redis://redis:6379
    volumes:
      - ${SERVER_DATA_DIR?:err}/${SERVICE_NAME}:/usr/src/paperless/data
      - ${SERVER_DATA_DIR?:err}/${SERVICE_NAME}/media:/usr/src/paperless/media
      - ${SERVER_DATA_DIR?:err}/${SERVICE_NAME}/export:/usr/src/paperless/export
      - ${SERVER_DATA_DIR?:err}/${SERVICE_NAME}/consume:/usr/src/paperless/consume
