version: "3.3"
services:
  rancher:
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    restart: unless-stopped
    privileged: true
    image: rancher/rancher:latest
    command: --no-cacerts
    volumes:
      - ${SERVER_CONFIG_DIR:?err}/${SERVICE_NAME:?err}:/var/lib/rancher