version: "3.9"
name: media-lab
services:

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: always
    environment:
      - UMASK=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    ports:
      - ${DELUGE_PORT}:8112
      - 58846:58846
      - 58946:58946/udp
    volumes:
      - config:/config
      - ${MEDIA_DIRECTORY}/downloads:/data/downloads
      - ${MEDIA_DIRECTORY}/movies:/data/movies
      - ${MEDIA_DIRECTORY}/shows:/data/shows
      - ${MEDIA_DIRECTORY}/books:/data/books
      - ${MEDIA_DIRECTORY}/podcasts:/data/podcasts

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: always
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - config:/config
      - ${MEDIA_DIRECTORY}/shows:/shows
      - ${MEDIA_DIRECTORY}/downloads:/data/downloads

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: always
    environment:
      - UMASK=022 #optional
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - config:/config
      - ${MEDIA_DIRECTORY}/movies:/movies
      - ${MEDIA_DIRECTORY}/downloads:/data/downloads

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: always
    ports:
      - ${BAZARR_PORT}:6767
    volumes:
      - config:/config
      - ${MEDIA_DIRECTORY}/movies:/movies
      - ${MEDIA_DIRECTORY}/shows:/shows

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: always
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - config:/config

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    restart: always
    ports:
      - ${OVERSEERR_PORT}:5055
    volumes:
      - config:/app/config

volumes:
  config:
  portainer-data: