version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  portainer:
    extends: 
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${SERVER_DATA_DIR?:err}/${SERVICE_NAME}:/data
