#7777:7777
#-v $HOME/terraria/world:/root/.local/share/Terraria/Worlds 
#--name="terraria" 
#-e WORLD_FILENAME=<.wld world_filename_here>
# ryshe/terraria:latest
version: "3.9"
services:
  terraria:
    image: ryshe/terraria:latest
    container_name: terraria
    command: -world /root/.local/share/Terraria/Worlds/master.wld
      -autocreate 2
    extends:
      file: ../game-server.docker-compose.yml
      service: game-server
    environment:
      - WORLD_FILENAME=master
    volumes:
      - ${SERVER_DATA_DIR/}/${SERVICE_NAME}:/root/.local/share/Terraria/Worlds
    labels:
      - "traefik.${PROTOCOL:?err}.routers.${SERVICE_NAME:?err}.rule=HostSNI(`${HOST_ADDRESS?:err}`)"

networks:
  proxy:
    external: true