version: "3.9"
services:
  terraria:
    image: ryshe/terraria:latest
    container_name: terraria
    command: -world /root/.local/share/Terraria/Worlds/Master_Of_Llama.wld -autocreate 3
    extends:
      file: ../game-server.docker-compose.yml
      service: game-server
    ports:
      - 7779:7777
    volumes:
      - ${SERVER_DATA_DIR:?err}/${SERVICE_NAME:?err}:/root/.local/share/Terraria/Worlds

networks:
  proxy:
    external: true