version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  sonarr:
    extends:
      file: ../proxied-media-service.docker-compose.yml
      service: proxied-media
    image: lscr.io/linuxserver/sonarr:develop
    volumes:
      - nas-share-shows:/data/shows:rw
