version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  radarr:
    extends:
      file: ../proxied-media-service.yml
      service: proxied-media
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - nas-share-movies:/data/movies
