version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  vaultwarden:
    extends:
      file: ../../../proxied-service.docker-compose.yml
      service: proxied
    image: vaultwarden/server:latest
    volumes:
      - ../../../data/${SERVICE_NAME}:/data