version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  vaultwarden:
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    image: vaultwarden/server:latest
    volumes:
      - ${SERVER_DATA_DIR?:err}/${SERVICE_NAME}:/data