version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  game-server:
    container_name: ${SERVICE_NAME:?err}
    environment:
      - TZ=US/Central
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.udp.routers.${SERVICE_NAME:?err}.entrypoints=${SERVICE_NAME:?err}-udp"
      - "traefik.udp.routers.${SERVICE_NAME:?err}.service=${SERVICE_NAME:?err}"
      - "traefik.udp.services.${SERVICE_NAME}.loadbalancer.server.port=${LOADBALANCE_PORT:?err}"
      - "traefik.tcp.routers.${SERVICE_NAME:?err}.entrypoints=${SERVICE_NAME:?err}-tcp"
      - "traefik.tcp.routers.${SERVICE_NAME:?err}.service=${SERVICE_NAME:?err}"
      - "traefik.tcp.services.${SERVICE_NAME}.loadbalancer.server.port=${LOADBALANCE_PORT:?err}"
      - "traefik.tcp.routers.${SERVICE_NAME:?err}.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.${SERVICE_NAME:?err}.tls=false"
      - "traefik.docker.network=proxy"
    networks:
      - proxy