version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password ${MYSQL_PASSWORD?:err}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:err}
  panel:
    &panel-environment
    # This URL should be the URL that your reverse proxy routes to the panel server
    APP_URL: "https://${SERVICE_NAME}.${HOST_ADDRESS}"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "US/Central"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    TRUSTED_PROXIES: "192.168.32.0/16" # Set this to your proxy IP
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    links:
      - mariadb
      - mariadb:database
      - redis
    volumes:
      - "${SERVER_CONFIG_DIR:?err}/pterodactyl/var/:/app/var/"
      - "${SERVER_CONFIG_DIR:?err}/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "${SERVER_DATA_DIR:?err}/pterodactyl/certs/:/etc/letsencrypt/"
      - "${SERVER_DATA_DIR:?err}/pterodactyl/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
