version: "3.9"
x-common:
  pterodactyl-database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "${DB_PASSWORD?:err}"
    MYSQL_ROOT_PASSWORD: "${DB_PASSWORD?:err}"
  pterodactyl-panel:
    &panel-environment
    APP_URL: "https://pterodactyl.lab.wiswellgrant.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "US/Central"
    APP_SERVICE_AUTHOR: "wiswellgrant@gmail.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "wiswellgrant@gmail.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  pterodactyl-database:
    image: mariadb:10.5
    container_name: pterodactyl-database
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${SERVER_DATA_DIR?:err}/${SERVICE_NAME?:err}/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    networks:
      - pterodactyl
  pterodactyl-cache:
    image: redis:alpine
    container_name: pterodactyl-cache
    restart: unless-stopped
    networks:
      - pterodactyl
  pterodactyl-panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl-panel
    extends:
      file: ${SERVER_DIR}/proxied-service.docker-compose.yml
      service: proxied
    links:
      - pterodactyl-database
      - pterodactyl-cache
    volumes:
      - "${SERVER_DATA_DIR?:err}/${SERVICE_NAME?:err}/var/:/app/var/"
      - "${SERVER_DATA_DIR?:err}/${SERVICE_NAME?:err}/nginx/:/etc/nginx/http.d/"
      - "${SERVER_DATA_DIR?:err}/${SERVICE_NAME?:err}/certs/:/etc/letsencrypt/"
      - "${SERVER_DATA_DIR?:err}/${SERVICE_NAME?:err}/logs/:/app/storage/logs"
    networks:
      - pterodactyl
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "pterodactyl-cache"
      DB_HOST: "pterodactyl-database"
      DB_PORT: "3306"

networks:
  pterodactyl:
    name: pterodactyl
