version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  transmission-openvpn:
    extends:
      file: ../proxied-media-service.docker-compose.yml
      service: proxied-media
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER?:err}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG?:err}
      - OPENVPN_USERNAME=${OPENVPN_USER?:err}
      - OPENVPN_PASSWORD=${OPENVPN_PASS?:err}
      - DISABLE_PORT_UPDATER=true
      - LOCAL_NETWORK=${LOCAL_NETWORK?:err}
    volumes:
      - ${SERVER_CONFIG_DIR?:err}/${SERVICE_NAME?:err}:/config
      - nas-share:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
