version: "3.9"
name: ${SERVICE_NAME:?err}
services:
  valheim:
    container_name: ${SERVICE_NAME:?err}
    image: lloesche/valheim-server
    extends:
      file: ../game-server.docker-compose.yml
      service: game-server
    environment:
      - TZ=US/Central
      - PUID=1000
      - PGID=1000
      - SERVER_NAME=${SERVICE_NAME:?err}
      - WORLD_NAME=Llama
      - SERVER_PASS=
      - SERVER_PUBLIC=false
      - UPDATE_IF_IDLE=true
      - BACKUPS=true
      - BEPINEX=true
      - BACKUPS_DIRECTORY=/data/backups
    volumes:
      - ${SERVER_CONFIG_DIR:?err}/${SERVICE_NAME:?err}:/config
      - ${SERVER_DATA_DIR:?err}/${SERVICE_NAME:?err}/backups:/data/backups
      - ${SERVER_DATA_DIR:?err}/${SERVICE_NAME:?err}:/opt/valheim
    networks:
      - proxy

networks:
  proxy:
    external: true