version: "3.9"
name: monitoring-stack
include:
  - prometheus/prometheus.docker-compose.yml
  - cadvisor/cadvisor.docker-compose.yml
  - grafana/grafana.docker-compose.yml
  - node-exporter/node-exporter.docker-compose.yml

networks:
  monitoring:
    name: monitoring